// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbhD_wE2XEk2XH7JRh3esPnfGELht9EDA',
    appId: '1:553973802298:web:462d8c4f4792c4afa1dc03',
    messagingSenderId: '553973802298',
    projectId: 'smartfeeder-1ba15',
    authDomain: 'smartfeeder-1ba15.firebaseapp.com',
    storageBucket: 'smartfeeder-1ba15.firebasestorage.app',
    measurementId: 'G-NE3HJ2J1V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcTTYVlRabQWmVtqxs-3LMLM64p_M-Mik',
    appId: '1:553973802298:android:d20de1f10bc59e82a1dc03',
    messagingSenderId: '553973802298',
    projectId: 'smartfeeder-1ba15',
    storageBucket: 'smartfeeder-1ba15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKUd3Ufzy55aKIHurW3jgfUGO8kho4jcw',
    appId: '1:553973802298:ios:148c2e8f89e898b4a1dc03',
    messagingSenderId: '553973802298',
    projectId: 'smartfeeder-1ba15',
    storageBucket: 'smartfeeder-1ba15.firebasestorage.app',
    iosBundleId: 'com.example.smartFeeder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKUd3Ufzy55aKIHurW3jgfUGO8kho4jcw',
    appId: '1:553973802298:ios:148c2e8f89e898b4a1dc03',
    messagingSenderId: '553973802298',
    projectId: 'smartfeeder-1ba15',
    storageBucket: 'smartfeeder-1ba15.firebasestorage.app',
    iosBundleId: 'com.example.smartFeeder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbhD_wE2XEk2XH7JRh3esPnfGELht9EDA',
    appId: '1:553973802298:web:3d8d2400a1332d7ca1dc03',
    messagingSenderId: '553973802298',
    projectId: 'smartfeeder-1ba15',
    authDomain: 'smartfeeder-1ba15.firebaseapp.com',
    storageBucket: 'smartfeeder-1ba15.firebasestorage.app',
    measurementId: 'G-BKWLE9VX57',
  );
}
